"""The paradigm router — people → agents (always), non-human stochastic process → parametric kernel.

The hybrid rule, with a HARD constraint the user set: if a question's outcome is generated by PEOPLE's
choices, behavior, opinions, votes, or reactions, it goes to the reasoning-agent society — never to a
parametric readout with LLM-supplied parameters (the logistic-with-arbitrary-variables failure we will not
regress to). Almost every social question is people. Only a genuinely non-human stochastic process — a
market price crossing a level, a physical measurement, a scheduled launch, a record — where no group's
decisions are the generative mechanism, is routed to main's parametric mechanisms (swm/api/mechanisms.py).

The classifier is deliberately BIASED toward "people": ties, ambiguity, and mixed cases all go to agents.
A cheap single call; on any failure it defaults to agents (fail toward the honest engine, never toward the
readout).
"""
from __future__ import annotations

from dataclasses import dataclass

from swm.engine.grounding import parse_json

# lexical fast-path: unmistakably human-decided outcomes skip the LLM call and go straight to agents
_PEOPLE = ("elect", "primary", "nominee", "nomination", "vote", "ballot", "referend", "president",
           "senate", "governor", "mayor", "congress", "parliament", "prime minister", "court", "justice",
           "ruling", "verdict", "confirm", "appoint", "impeach", "resign", "coalition", "approval",
           "poll", "win the", "beat", "defeat", "nominate", "endorse", "strike", "boycott", "protest",
           "reply", "respond", "email", "message", "buy", "adopt", "subscribe", "churn", "headline",
           "campaign", "negotiat", "deal", "treaty", "hire", "fire", "quit", "boss", "customer", "voter")
# unmistakably non-human stochastic processes → parametric (still LLM-checked unless clearly here)
_PROCESS = ("price", "bitcoin", "btc", "ether", "stock", "index", "s&p", "nasdaq", "yield", "inflation",
            "gdp", "temperature", "rainfall", "earthquake", "hurricane", "launch", "eclipse", "record high",
            "record low", "exchange rate")


_PROMPT = """Classify how this question's outcome is GENERATED.
QUESTION: {q}

Answer "people" if the outcome is produced by the choices, behavior, opinions, votes, reactions, or
decisions of humans (elections, approvals, court/committee rulings, whether someone acts/replies/buys,
adoption, negotiations, unrest — almost everything social). Answer "process" ONLY if it is a genuinely
non-human stochastic process where NO group's decisions are the mechanism — a market price crossing a
level, a physical/weather measurement, a scheduled astronomical event, a sports/statistical record.
When in doubt, or if people's behavior is any meaningful part of it, answer "people".
Return ONLY JSON: {{"kind": "people" | "process", "why": "<8 words>"}}"""


# CONTEST / ANNOUNCEMENT markers — people questions, but NOT social-deliberation ones. A sports game is a
# physical contest (main's `contest` kernel); a product launch/announcement is an arrival (main's `arrival`
# kernel). The agent-deliberation panel is confidently WRONG on these (n=127: sports -2.5, tech -2.7), so they
# route to the parametric kernel / a base-rate anchor instead of the panel.
# Unambiguous SPORTS/contest markers only — deliberately excludes words that collide with elections
# ("race", "beat", "defeat", "final") so "the mayoral race" / "will X beat Y in the election" stay deliberation.
_CONTEST = (" vs ", " vs.", " v ", " v.", "playoff", "grand prix", "clasico", "clásico", "derby",
            "world series", "super bowl", "world cup", "champions league", "premier league", "la liga",
            " nba ", " nfl ", " mlb ", " nhl ", " ufc ", "olympic", "tournament", "knockout", "quarterfinal",
            "semifinal", "heavyweight", "wrestlemania", "test match", "grand slam")
_ANNOUNCE = ("announce", "release", "launch", "unveil", " ship ", "reveal", "debut", "roll out", "rollout",
             "made available", "broadly available", "become available", "generally available")


@dataclass
class ParadigmRouter:
    llm: object = None                     # cheap classifier backend; None ⇒ lexical-only (people-biased)

    def binary_kind(self, question: str) -> str:
        """For a people-domain binary event, is it social DELIBERATION (elections, policy, appointments,
        adoption — the agent panel's turf) or a CONTEST / ANNOUNCEMENT (a physical contest or a product/
        release event — the parametric kernel's turf)? Lexical + people-biased; defaults to deliberation."""
        ql = question.lower()
        if any(w in ql for w in _CONTEST):
            return "contest"
        if any(w in ql for w in _ANNOUNCE):
            return "announcement"
        return "deliberation"

    def route(self, question: str) -> str:
        """Return 'agents' or 'parametric'. Biased hard toward 'agents'."""
        return self.route_with_reason(question)[0]

    def route_with_reason(self, question: str) -> tuple:
        """(route, why) — the system must LOG why it selected a paradigm (vision gap 4): the operative rule is
        'does the outcome materially depend on human decisions/beliefs/reactions/coordination? → agents'."""
        ql = question.lower()
        hit = next((w for w in _PEOPLE if w in ql), None)
        if hit:
            return "agents", f"human-decided outcome (lexical: {hit!r}) → grounded agents, hard rule"
        if self.llm is None:
            p = next((w for w in _PROCESS if w in ql), None)
            return (("parametric", f"non-human stochastic process (lexical: {p!r}); no human decision is "
                                   f"the generative mechanism") if p else
                    ("agents", "no unmistakable non-human marker; ambiguity fails toward agents (hard rule)"))
        try:
            r = parse_json(self.llm(_PROMPT.format(q=question))) or {}
        except Exception:
            return "agents", "classifier failed → fail toward the honest engine (hard rule)"
        if r.get("kind") == "process":
            return "parametric", f"classifier: non-human process ({str(r.get('why', ''))[:80]})"
        return "agents", f"classifier: human-generated outcome ({str(r.get('why', ''))[:80]})"
