"""The paradigm router — people → agents (always), non-human stochastic process → parametric kernel.

The hybrid rule, with a HARD constraint the user set: if a question's outcome is generated by PEOPLE's
choices, behavior, opinions, votes, or reactions, it goes to the reasoning-agent society — never to a
parametric readout with LLM-supplied parameters (the logistic-with-arbitrary-variables failure we will not
regress to). Almost every social question is people. Only a genuinely non-human stochastic process — a
market price crossing a level, a physical measurement, a scheduled launch, a record — where no group's
decisions are the generative mechanism, is routed to main's parametric mechanisms (swm/api/mechanisms.py).

The classifier is deliberately BIASED toward "people": ties, ambiguity, and mixed cases all go to agents.
A cheap single call; on any failure it defaults to agents (fail toward the honest engine, never toward the
readout).
"""
from __future__ import annotations

from dataclasses import dataclass

from swm.engine.grounding import parse_json

# lexical fast-path: unmistakably human-decided outcomes skip the LLM call and go straight to agents
_PEOPLE = ("elect", "primary", "nominee", "nomination", "vote", "ballot", "referend", "president",
           "senate", "governor", "mayor", "congress", "parliament", "prime minister", "court", "justice",
           "ruling", "verdict", "confirm", "appoint", "impeach", "resign", "coalition", "approval",
           "poll", "win the", "beat", "defeat", "nominate", "endorse", "strike", "boycott", "protest",
           "reply", "respond", "email", "message", "buy", "adopt", "subscribe", "churn", "headline",
           "campaign", "negotiat", "deal", "treaty", "hire", "fire", "quit", "boss", "customer", "voter")
# unmistakably non-human stochastic processes → parametric (still LLM-checked unless clearly here)
_PROCESS = ("price", "bitcoin", "btc", "ether", "stock", "index", "s&p", "nasdaq", "yield", "inflation",
            "gdp", "temperature", "rainfall", "earthquake", "hurricane", "launch", "eclipse", "record high",
            "record low", "exchange rate")


_PROMPT = """Classify how this question's outcome is GENERATED.
QUESTION: {q}

Answer "people" if the outcome is produced by the choices, behavior, opinions, votes, reactions, or
decisions of humans (elections, approvals, court/committee rulings, whether someone acts/replies/buys,
adoption, negotiations, unrest — almost everything social). Answer "process" ONLY if it is a genuinely
non-human stochastic process where NO group's decisions are the mechanism — a market price crossing a
level, a physical/weather measurement, a scheduled astronomical event, a sports/statistical record.
When in doubt, or if people's behavior is any meaningful part of it, answer "people".
Return ONLY JSON: {{"kind": "people" | "process", "why": "<8 words>"}}"""


@dataclass
class ParadigmRouter:
    llm: object = None                     # cheap classifier backend; None ⇒ lexical-only (people-biased)

    def route(self, question: str) -> str:
        """Return 'agents' or 'parametric'. Biased hard toward 'agents'."""
        ql = question.lower()
        if any(w in ql for w in _PEOPLE):
            return "agents"                                # unambiguously human-decided → agents, no call
        if self.llm is None:
            # no classifier: only divert the unmistakable non-human processes, else agents
            return "parametric" if any(w in ql for w in _PROCESS) else "agents"
        try:
            r = parse_json(self.llm(_PROMPT.format(q=question))) or {}
        except Exception:
            return "agents"                                # fail toward the honest engine
        return "parametric" if r.get("kind") == "process" else "agents"
