"""QUARANTINED LEGACY ABLATIONS — explicitly NOT the production path.

This module holds the pre-event-driven periodic scheduler for benchmark comparison ONLY. The
production runtime (unified_runtime) never imports it; enforcement tests
(tests/test_temporal_enforcement.py) fail the build if any production module does. Calling the
ablation requires the literal acknowledgement token so no code path can drift into using it as
a quiet default.

What lives here and why it was removed from production:

  legacy_periodic_review_ablation — the old `deepen_trajectory`: split the horizon into 2–14
  evenly spaced points, take the six highest-sensitivity actors, and schedule every one of them
  a "periodic strategic review" decision at every point. That is a scheduler convenience, not a
  representation of how real decisions arise: production actors now decide only when a real
  DecisionTrigger occurs (newly noticed information, a deadline, an institutional stage, a
  promised follow-up, …) generated by the scenario temporal compiler.
"""
from __future__ import annotations

ABLATION_TOKEN = "I_UNDERSTAND_THIS_IS_A_LEGACY_ABLATION_NOT_PRODUCTION"


def legacy_periodic_review_ablation(plan, req, *, cadence_days=None, acknowledge: str = ""):
    """The quarantined periodic scheduler (formerly fidelity.deepen_trajectory). Benchmarks
    comparing old-vs-new temporal behavior call this with the acknowledgement token; anything
    else gets a loud refusal."""
    if acknowledge != ABLATION_TOKEN:
        raise PermissionError(
            "legacy_periodic_review_ablation is a QUARANTINED ablation, not a production "
            "scheduler. Production uses scenario-generated decision triggers "
            "(temporal_compiler/temporal_runtime). Pass acknowledge=ABLATION_TOKEN only from "
            "an explicit old-vs-new benchmark.")
    from swm.world_model_v2.fidelity import _candidate_actions
    horizon_days = max(1.0, (plan.horizon_ts - plan.as_of) / 86400.0)
    cad = cadence_days or max(1.0, horizon_days / 6.0)
    cad = max(0.5, min(cad, horizon_days / 2.0))
    n_points = max(2, min(14, int(horizon_days / cad)))
    actors = [e for e in plan.entities if isinstance(e, dict) and e.get("id")]
    actors.sort(key=lambda e: -float(e.get("sensitivity", 0.5) or 0.5))
    strategic = actors[:6] if req.get("phase4_actor_policy", {}).get("required") else []
    declared = {str(e.get("id")) for e in plan.entities if isinstance(e, dict)}
    pathways = list(getattr(plan, "_declared_pathways", None) or [])
    n_added = 0
    for k in range(1, n_points + 1):
        ts = plan.as_of + (k / (n_points + 1)) * (plan.horizon_ts - plan.as_of)
        for a in strategic:
            aid = str(a.get("id"))
            if aid not in declared:
                continue
            plan.scheduled_events.append({
                "etype": "decision_opportunity", "ts": ts, "participants": [aid],
                "payload": {"situation": f"periodic strategic review ({k}/{n_points})",
                            "actions": _candidate_actions(a, pathways),
                            "_legacy_ablation": True}})
            n_added += 1
    return {"horizon_days": round(horizon_days, 1), "cadence_days": round(cad, 1),
            "decision_points": n_points, "strategic_actors": len(strategic),
            "pathway_informed_candidates": bool(pathways),
            "decision_events_added": n_added, "legacy_ablation": True}
