"""Numerical & physical state — Phase 1.6. Arbitrary typed quantities with units, uncertainty, provenance.

Not a fixed domain list: the compiler infers which quantities a scenario needs and registers their types
(dimension/units/range/observation model/temporal resolution). Validated parametric mechanisms may update
them; human behavior must NEVER be generated by the legacy arbitrary-variable logistic compiler (that path
stays quarantined in v1 and is not importable from this package — pinned by test).
"""
from __future__ import annotations

from dataclasses import dataclass, field

from swm.world_model_v2.state import Provenance, StateField

_QUANTITY_TYPES: dict = {}


def register_quantity_type(name: str, *, units: str, lo=None, hi=None, temporal_resolution: str = "",
                           observation_model: str = ""):
    """Typed quantity registry: dimensions/units/range/obs-model declared before use."""
    _QUANTITY_TYPES[name] = {"units": units, "lo": lo, "hi": hi,
                             "temporal_resolution": temporal_resolution,
                             "observation_model": observation_model}
    return name


# a starter set — examples, not a closed list
for _n, _u, _lo, _hi in (("price", "usd", 0, None), ("poll_share", "share", 0.0, 1.0),
                         ("budget", "usd", 0, None), ("inventory", "count", 0, None),
                         ("attention_hours", "hours/day", 0, 24), ("capacity", "count", 0, None),
                         ("procedural_stage", "enum", None, None), ("queue_depth", "count", 0, None)):
    register_quantity_type(_n, units=_u, lo=_lo, hi=_hi)


@dataclass
class Quantity:
    name: str
    qtype: str                            # a registered quantity type
    value: float = None
    sd: float = None                      # uncertainty (None = treated as exact/observed)
    timestamp: float = 0.0
    prov: Provenance = field(default_factory=Provenance)

    def __post_init__(self):
        if self.qtype not in _QUANTITY_TYPES:
            raise KeyError(f"unregistered quantity type {self.qtype!r} — register_quantity_type() first")

    def units(self):
        return _QUANTITY_TYPES[self.qtype]["units"]

    def clamp(self):
        t = _QUANTITY_TYPES[self.qtype]
        if isinstance(self.value, (int, float)):
            if t["lo"] is not None:
                self.value = max(t["lo"], self.value)
            if t["hi"] is not None:
                self.value = min(t["hi"], self.value)
        return self
